version: '3.0'
services:
  
  openvpn:
    image: llnpce/openvpn:0.3
    ports:
      - "${PORT}:1194/udp"
    devices:
      - "/dev/net/tun:/dev/net/tun"
    cap_add:
      - NET_ADMIN
    volumes:
      - ".:/etc/openvpn"
      - "/var/log/openvpn:/var/log/openvpn/"